objects-$(CONFIG_ROLE_SLAVE)+=slave.o
objects-$(CONFIG_ROLE_UISP)+=uisp-app.o cb.o


subdirs-$(CONFIG_ARCH_AVR)+=avr/
subdirs-y+=hacks/

objects-$(CONFIG_BOOTCOND_TIMED)+=bootcond-timed.o
objects-$(CONFIG_PART_DUMMY)+=dummypart.o

subdirs-$(CONFIG_ROLE_LIB_USERSPACE)+= native/

